config/routes.rb
Rails.application.routes.draw do

  scope '/dashboard' do
      resources :parts, :vendors, :policies, :roles
      get 'part/search', to: 'parts#search'
  end
  get 'dashboard_unauth/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "dashboard#index"

  get 'dashboard/users', to: 'users#index'
  put 'dashboard/users/:id', to: 'users#update_role', as: :user_update_roles

  get 'dashboard_unauth/orders', to: 'dashboard_unauth#orders'
  get 'dashboard_unauth/products', to: 'dashboard_unauth#products'
  get 'dashboard_unauth/customers', to: 'dashboard_unauth#customers'
  get 'dashboard_unauth/users', to: 'dashboard_unauth#users'
  get 'dashboard_unauth/departments', to: 'dashboard_unauth#departments'



end

app/models/policy.rb
class Policy < ApplicationRecord
	has_many :policy_roles
	has_many :users, through: :policy_users
	has_many :roles, through: :policy_roles
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  before_action :set_policy, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  layout 'dashboard'

  # GET /policies or /policies.json
  def index
    @policies = Policy.all
  end

  # GET /policies/1 or /policies/1.json
  def show
  end

  # GET /policies/new
  def new
    @policy = Policy.new
  end

  # GET /policies/1/edit
  def edit
  end

  # POST /policies or /policies.json
  def create
    @policy = Policy.new(policy_params)

    respond_to do |format|
      if @policy.save
        format.html { redirect_to @policy, notice: "Policy was successfully created." }
        format.json { render :show, status: :created, location: @policy }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /policies/1 or /policies/1.json
  def update
    respond_to do |format|
      if @policy.update(policy_params)
        format.html { redirect_to @policy, notice: "Policy was successfully updated." }
        format.json { render :show, status: :ok, location: @policy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /policies/1 or /policies/1.json
  def destroy
    @policy.destroy
    respond_to do |format|
      format.html { redirect_to policies_url, notice: "Policy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_policy
      @policy = Policy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def policy_params
      params.require(:policy).permit(:name, role_ids: [])
    end
end

app/helpers/policies_helper.rb
module PoliciesHelper


	def options_for_role
	  	Role.all.map { |e| [e.name, e.id]  }
	end

end

app/views/policies/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_with(model: policy) do |form| %>
      <% if policy.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(policy.errors.count, "error") %> prohibited this policy from being saved:</h2>

          <ul>
            <% policy.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :roles %>
        <%= form.select :role_ids, options_for_role, {}, {:multiple => true, class: 'form-control' } %>
      </div>

      <div class="actions">
        <%= form.submit "Submit", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/policies/edit.html.erb
<h1>Editing Policy</h1>

<%= render 'form', policy: @policy %>

<%= link_to 'Show', @policy %> |
<%= link_to 'Back', policies_path %>

app/views/policies/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Policy</h2>
  <div class="table-responsive">

    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>Name</th>
          <th>Roles</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @policies.each do |policy| %>
          <tr>
            <td><%= policy.name %></td>
            <td><%= policy.roles.map(&:name) %></td>
            <td><%= link_to 'Show', policy %> | <%= link_to 'Edit', edit_policy_path(policy) %> | <%= link_to 'Destroy', policy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

<br>

<%= link_to 'New Policy', new_policy_path %>

app/views/policies/new.html.erb
<h1>New Policy</h1>

<%= render 'form', policy: @policy %>

<%= link_to 'Back', policies_path %>

app/views/policies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @policy.name %>
</p>

<%= link_to 'Edit', edit_policy_path(@policy) %> |
<%= link_to 'Back', policies_path %>